In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target.copy()
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# 转换为二分类问题
y[y!=0] = 1
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

logistic_regression = LogisticRegression()
logistic_regression.fit(X_train,y_train)
y_predict = logistic_regression.predict(X_test)

# 手动实现

In [5]:
TN = np.sum((y_predict==0)&(y_test==0))
TN

np.int64(10)

In [6]:
FP = np.sum((y_predict==1)&(y_test==0))
FP

np.int64(0)

In [7]:
FN = np.sum((y_predict==0)&(y_test==1))
FN

np.int64(0)

In [8]:
TP = np.sum((y_predict==1)&(y_test==1))
TP

np.int64(28)

In [9]:
confusion_matrix = np.array([
    [TN, FP],
    [FN, TP]
])

confusion_matrix

array([[10,  0],
       [ 0, 28]])

In [10]:
precision = TP/ (TP+FP)
precision

np.float64(1.0)

In [11]:
recall = TP/(FN+TP)
recall

np.float64(1.0)

In [12]:
f1_score = 2*precision*recall /(precision+recall)
f1_score

np.float64(1.0)

# scikit-learn封装实现

In [13]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_predict)

array([[10,  0],
       [ 0, 28]])

In [14]:
from sklearn.metrics import precision_score

precision_score(y_test,y_predict)

1.0

In [15]:
from sklearn.metrics import recall_score

recall_score(y_test,y_predict)

1.0

In [16]:
from sklearn.metrics import f1_score

f1_score(y_test,y_predict)

1.0

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

1.0