### 最大最小值

In [1]:
import numpy as np
X = np.arange(5000000)
X

array([      0,       1,       2, ..., 4999997, 4999998, 4999999],
      shape=(5000000,))

In [2]:
np.min(X)

np.int64(0)

In [ ]:
np.max(X) 

np.int64(4999999)

In [4]:
%time min(X)

CPU times: user 457 ms, sys: 35.9 ms, total: 493 ms
Wall time: 448 ms


np.int64(0)

In [5]:
%time np.min(X)

CPU times: user 4.46 ms, sys: 1.92 ms, total: 6.38 ms
Wall time: 4.03 ms


np.int64(0)

In [6]:
Y = X.reshape(5, -1)
Y

array([[      0,       1,       2, ...,  999997,  999998,  999999],
       [1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999],
       [2000000, 2000001, 2000002, ..., 2999997, 2999998, 2999999],
       [3000000, 3000001, 3000002, ..., 3999997, 3999998, 3999999],
       [4000000, 4000001, 4000002, ..., 4999997, 4999998, 4999999]],
      shape=(5, 1000000))

In [7]:
np.min(Y, axis = 0)

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

In [8]:
np.min(Y, axis = 1)

array([      0, 1000000, 2000000, 3000000, 4000000])

### 常见统计量

In [9]:
X = np.linspace(1, 20, 20).reshape(4, 5)
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [10]:
np.sum(X)

np.float64(210.0)

In [11]:
np.sum(X, axis = 0)

array([34., 38., 42., 46., 50.])

In [12]:
np.sum(X, axis = 1)

array([15., 40., 65., 90.])

In [ ]:
# 均值
np.mean(X)

np.float64(10.5)

In [ ]:
# 中位数
np.median(X)

np.float64(10.5)

In [ ]:
# 标准差
np.std(X)

np.float64(5.766281297335398)

In [ ]:
# 方差
np.var(X)

np.float64(33.25)

In [ ]:
# 创建均值是0,标准差是10, 100000个数的数组
Z = np.random.normal(0, 10, 100000)
np.mean(Z), np.std(Z)

(np.float64(0.010843815138870864), np.float64(9.994941560981802))

### 补充内容

In [ ]:
# 计算最大值和最小值的差
np.ptp(X)

np.float64(19.0)

In [24]:
q = np.linspace(0, 100, 5)
q

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
# 计算指定百分位的数 
q, np.percentile(X, q)

(array([  0.,  25.,  50.,  75., 100.]),
 array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]))

In [ ]:
# 求累加
np.cumsum(X, axis = 1)

array([[ 1.,  3.,  6., 10., 15.],
       [ 6., 13., 21., 30., 40.],
       [11., 23., 36., 50., 65.],
       [16., 33., 51., 70., 90.]])

In [ ]:
# 计算行(axis=1)相邻的差
np.diff(X, axis = 1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 计算行(axis=1)的乘积  
# 第一个数= 1*2*3*4*5
np.prod(X, axis = 1)

array([1.20000e+02, 3.02400e+04, 3.60360e+05, 1.86048e+06])