## 最大值 最小值

In [ ]:
import numpy as np 
# 均值为0,标准差为1
x = np.random.normal(0,1,size=1000000)
x

array([ 0.36182028,  0.63720631, -1.07314723, ...,  0.11131101,
       -0.05452148, -0.35576663], shape=(1000000,))

In [2]:
np.min(x)

np.float64(-4.700922708081516)

In [ ]:
# 最小值的索引
np.argmin(x)

np.int64(410681)

In [4]:
x[286411]

np.float64(0.2902714717580671)

In [5]:
np.max(x)

np.float64(4.714856509696351)

In [ ]:
# 最大值的索引
x[np.argmax(x)]

np.float64(4.714856509696351)

## 排序

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# shuffle 随机打乱顺序
np.random.shuffle(x)
x

array([6, 7, 0, 3, 2, 8, 4, 5, 1, 9])

In [ ]:
# 排序,不会改变原数组的顺序
np.sort(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x

array([6, 7, 0, 3, 2, 8, 4, 5, 1, 9])

In [ ]:
# python原生排序,会改变原始数组顺序
x.sort()

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 使用索引

In [23]:
np.random.shuffle(x)
x

array([0, 9, 7, 2, 5, 1, 6, 3, 8, 4])

In [ ]:
# 返回排序后的元素索引
np.argsort(x)

array([8, 3, 1, 6, 0, 5, 9, 2, 4, 7])

## partition 分区

In [ ]:
# 按第5个元素分区 , 小于5的放左边,大于等于5的放右边
np.partition(x, 5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 返回索引
np.argpartition(x, 5)

array([0, 5, 3, 7, 9, 4, 6, 2, 8, 1])

## 高维情况

In [18]:
X = np.random.randint(10, size=(5,5))
X

array([[9, 0, 0, 8, 9],
       [1, 5, 7, 4, 2],
       [3, 3, 4, 8, 1],
       [8, 0, 4, 8, 5],
       [1, 8, 5, 0, 3]])

In [19]:
np.sort(X)

array([[0, 0, 8, 9, 9],
       [1, 2, 4, 5, 7],
       [1, 3, 3, 4, 8],
       [0, 4, 5, 8, 8],
       [0, 1, 3, 5, 8]])

In [20]:
np.argsort(X, axis=1)

array([[1, 2, 3, 0, 4],
       [0, 4, 3, 1, 2],
       [4, 0, 1, 2, 3],
       [1, 2, 4, 0, 3],
       [3, 0, 4, 2, 1]])

In [21]:
np.partition(X,2, axis=1)

array([[0, 0, 8, 9, 9],
       [1, 2, 4, 5, 7],
       [1, 3, 3, 4, 8],
       [0, 4, 5, 8, 8],
       [0, 1, 3, 5, 8]])

In [22]:
np.argpartition(X,2,axis=1)

array([[1, 2, 3, 0, 4],
       [0, 4, 3, 1, 2],
       [4, 0, 1, 2, 3],
       [1, 2, 4, 0, 3],
       [3, 0, 4, 2, 1]])