In [25]:
import numpy as np

# 1. 创建Numpy数组

In [26]:
a = np.array([1,2,3,4,5,6])  # 一维数组/向量
a

array([1, 2, 3, 4, 5, 6])

In [27]:
# 二维数组/矩阵
A = np.array(
    [
        [1,2,3],
        [5,6,7]
    ]
)
A

array([[1, 2, 3],
       [5, 6, 7]])

# 2. Numpy数组的属性

## ndim-维度

In [28]:
a.ndim

1

In [29]:
A.ndim

2

## shape - 数组的形状

In [30]:
a.shape

(6,)

In [31]:
A.shape
# (2, 3)表示2行3列

(2, 3)

## size - 元素个数

In [32]:
a.size

6

In [33]:
A.size

6

## dtype - 数据类型

In [34]:
a.dtype

dtype('int64')

In [35]:
A.dtype

dtype('int64')

## itemsize 元素内存大小

In [ ]:
#每一个元素的内存大小
A.itemsize

8

# 3. 创建数组的便捷函数

##  ones - 创建元素是1的数组

In [36]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
# 默认使用的float64数据类型
np.ones(8).dtype

dtype('float64')

In [38]:
# 指定数据类型为int64
np.ones(8,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
# 创建2行4列数组
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# 创建形状相同的数组
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1]])

## zeros - 创建元素是0的数组

In [41]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

## full - 创建指定数值的数组

In [44]:

np.full(8,666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [45]:
np.full((2,4),666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

In [46]:
np.full_like(A, 666)

array([[666, 666, 666],
       [666, 666, 666]])

## empty - 创建指定形状的空数组(元素是随机值)

In [47]:
np.empty(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.empty_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

## arange - 创建等差数组

In [50]:
# 创建数据范围[0,10),步长1的数组(0和1都是默认值)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# 创建数据范围[1,20),步长2的数组
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
# reshape 设置形状
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## linspace 创建指定元素个数的等差数组

In [75]:
# 创建数组,数据范围[0,10],元素个数5个
np.linspace(0,10,5,dtype="int64")

array([ 0,  2,  5,  7, 10])

# 4. random模块

## random

In [ ]:
# 返回[0,1)之间的随机数
np.random.random()

0.9594551235264691

In [ ]:
# 生成5个[0,1)之间的随机数
np.random.random(5)

array([0.52414204, 0.03643288, 0.72687158, 0.00390984, 0.050294  ])

In [ ]:
# 返回一个指定形状的随机数数组
np.random.random((2,4))

array([[0.69763054, 0.81210236, 0.22783067, 0.03758508],
       [0.27630252, 0.13085244, 0.37448534, 0.76955431]])

## rand
> 和random区别是参数传递方式不同,效果都一样
* random使用元祖传参, rand不用

In [78]:
np.random.rand()

0.9919923158752376

In [79]:
np.random.rand(5)

array([0.2122575 , 0.94737066, 0.45154055, 0.99879467, 0.64750149])

In [81]:
np.random.rand(2,4)

array([[0.46848893, 0.23431308, 0.08982494, 0.67940357],
       [0.65592832, 0.0039444 , 0.06654134, 0.00112109]])

## randint 指定数据区间的随机int数

In [82]:
np.random.randint(5)

4

In [83]:
# 返回[5,10)区间的整数
np.random.randint(5,10)

6

In [84]:
np.random.randint(5,10,size=8)

array([5, 5, 9, 5, 9, 6, 7, 6])

In [85]:
np.random.randint(5,10,size=(2,4))

array([[6, 8, 7, 6],
       [6, 9, 9, 9]])

## seed - 指定随机种子

In [96]:
# 每次返回的随机值都是一样的
np.random.seed(666)
np.random.randint(5,10,size=(2,4))

array([[9, 7, 6, 9],
       [8, 8, 9, 9]])

## randn 返回标准正态分布的随机值

In [103]:
# 返回标准正态分布的随机值, 均值为0,标准差为1
np.random.randn(5)

array([0.84463262, 0.27721986, 0.85290153, 0.1945996 , 1.31063772])

In [105]:
np.random.randn(2,4)

array([[ 0.29655378, -0.3126795 , -0.61130127, -0.8217515 ],
       [ 0.8971227 ,  0.13607861, -0.2586548 ,  1.11076564]])

## normal - 返回可以设置均值和方差的随机值

In [110]:
# 默认均值为0,标准差为1
np.random.normal()

-0.9139589871488081

In [111]:
# 均值10,标准差 1000, 生成20个
np.random.normal(10,100,20)

array([ -48.49492958,  -48.39237081,    9.28183738, -184.29666053,
        -12.02022763, -147.05176264,   -8.62669391,   36.64167135,
        -50.91154588,  -98.08142141,  166.9808226 ,    0.84546907,
        -79.69317904,  123.33561037,  182.20470793,   70.93781785,
         69.03514395,  -53.49463372,  196.28895645,  -76.98123368])

In [112]:
# 均值10,标准差 1000, 生成4*5个随机值
np.random.normal(10,100,size=(4,5))

array([[ -68.45173996,  -30.77066124,  115.3000946 ,  -53.826851  ,
         237.52404065],
       [ 191.73648768,    3.76591424,   35.14009023,   18.30772216,
          46.24901024],
       [   1.48632425,   98.36277176, -189.20935775,    3.99331353,
         -68.30028776],
       [-151.3623447 , -169.70003058,  -20.58024488,   76.99216959,
         150.28544538]])

## uniform 指定数据区间的随机浮点数

In [ ]:
# 默认生成 [0,1)之间的随机数
np.random.uniform()

0.5018935081312759

In [ ]:
# 生成 1-5之间的随机数
np.random.uniform(1,5)

2.993092519645257

In [113]:
np.random.uniform(1,5,(3,4))

array([[1.92413988, 3.19308173, 2.2782408 , 3.9208452 ],
       [4.7702893 , 4.09769009, 4.45516306, 4.31614461],
       [4.25518587, 3.52664935, 3.75241702, 1.38022167]])

# 5. 查询函数文档

In [116]:
np.random.uniform?

Signature: np.random.uniform(low=0.0, high=1.0, size=None)
Docstring:
uniform(low=0.0, high=1.0, size=None)

Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval
``[low, high)`` (includes low, but excludes high).  In other words,
any value within the given interval is equally likely to be drawn
by `uniform`.

.. note::
    New code should use the `~numpy.random.Generator.uniform`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval.  All values generated will be
    greater than or equal to low.  The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval.  All values generated will be
    less than or equal to high.  The high limit may be included in the 
    returned array of floats due to floating-point rounding in the 
    equa

In [117]:
help(np.random.uniform)

Help on method uniform in module numpy.random:

uniform(low=0.0, high=1.0, size=None) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)

    Draw samples from a uniform distribution.

    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.

    .. note::
        New code should use the `~numpy.random.Generator.uniform`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less 