# 基础索引
> 掌握了正向索引和反向索引,就知道如何取数组中的元素

|数组定义|1|3|5|7|9|
|-|-|-|-|-|-|
|正向索引|0|1|2|3|4|
|反向索引|-5|-4|-3|-2|-1|

In [1]:
import numpy as np

In [ ]:
# 一维数组  也看作：向量,一般用小写字母表示
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 二维数组 看作是：矩阵,一般用大写字母表示
A = np.arange(20).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 一维数组

*  a[起始索引:结束索引(不包含):步长]
    * 步长: 正数则正着取数,负数则反着取数 


In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[0]

np.int64(0)

In [31]:
a[-1]

np.int64(9)

In [32]:
a[0:5]

array([0, 1, 2, 3, 4])

In [9]:
a[:5]

array([0, 1, 2, 3, 4])

In [10]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [11]:
a[-3:]

array([7, 8, 9])

In [33]:
# 左边不写默认是0,右边不写默认是最后一个元素的索引
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 指定步长取数
a[::2]

array([0, 2, 4, 6, 8])

## 二维数组

In [14]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
A[0,0]

np.int64(0)

In [37]:
A[0,:] #取第一行的数组 可以简写为 A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[-1] #取最后一行

array([15, 16, 17, 18, 19])

In [ ]:
A[:,0] #取第一列

array([ 0,  5, 10, 15])

In [38]:
A[:,-1] #取最后一列

array([ 4,  9, 14, 19])

In [ ]:
A[:2,:4] # 取前2行,前4列的数据

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [ ]:
A[::-1,::-1] #倒序取所有行,所有列

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

* numpy的切片是直接修改的原数组
* 如果要单独修改可以使用copy()方法

In [23]:
X = A[:2,:3]
X

array([[0, 1, 2],
       [5, 6, 7]])

In [24]:
X[0,0] = 666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [25]:
A

array([[666,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [26]:
A[0,0] = 0
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
X

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
X = A[:2,:3].copy()
X

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
X[0,0] = 666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [30]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])