# 数组的合并

In [1]:
import numpy as np

In [2]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a = np.array([6,6,6,6])
a

array([6, 6, 6, 6])

## concatenate
* axis: 0:垂直合并(默认), 1: 水平合并

In [ ]:
#不同维度的数组是无法合并的
np.concatenate((X,a)) 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [6]:
# a.reshape(1,4) 把a转成1*4的2维数组
A = np.concatenate((X,a.reshape(1,4)))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

## vstack 垂直合并

In [ ]:
# vstack在竖直方向上堆叠(合并), 就是把X放到a上面
np.vstack((X,a))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

## hstack - 水平合并

In [ ]:
B = np.full((3,2),666)
B

array([[666, 666],
       [666, 666],
       [666, 666]])

In [ ]:
# # hstack在水平方向上合并, 就是把X放到a上面
np.hstack((X,B))

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

In [ ]:
np.concatenate((X,B),axis=1)

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

# 数组的拆分

In [ ]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## split

In [ ]:
# [-1] 拆分的索引
np.split(X,[-1], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [ ]:
X1,X2 = np.split(X,[-1], axis=1)

In [ ]:
X1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
X2

array([[ 3],
       [ 7],
       [11]])

## vsplit/hsplit

In [9]:
X1,X2=np.vsplit(X,[2])   
X1,X2

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]))

In [ ]:
# [1,3]可以理解为切2刀,分别在1,3索引位置
np.hsplit(X,[1,3])  

[array([[0],
        [4],
        [8]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3],
        [ 7],
        [11]])]